/**
 * Aquador Catalogue Data
 * Complete product inventory for AI assistant
 */

export interface CatalogueProduct {
  number: string;
  name: string;
  brand: string;
  gender: 'Men' | 'Women' | 'Unisex';
  type: 'perfume' | 'essence-oil' | 'body-lotion';
  searchTerms?: string[]; // For better matching
}

export const catalogueProducts: CatalogueProduct[] = [
  // Main Perfumes (1-354)
  { number: '1', name: 'Interlude Man', brand: 'Amouage', gender: 'Men', type: 'perfume' },
  { number: '2', name: 'Lyric Men', brand: 'Amouage', gender: 'Men', type: 'perfume' },
  { number: '3', name: 'Jubilation XXV', brand: 'Amouage', gender: 'Men', type: 'perfume' },
  { number: '4', name: 'Stronger with You Oud', brand: 'Emporio Armani', gender: 'Men', type: 'perfume' },
  { number: '5', name: 'Scandal Pour Homme', brand: 'Jean Paul Gaultier', gender: 'Men', type: 'perfume' },
  { number: '6', name: 'The Tragedy of Lord George', brand: "Penhaligon's", gender: 'Men', type: 'perfume' },
  { number: '7', name: 'Signature', brand: "Designed by Aquad'or", gender: 'Unisex', type: 'perfume' },
  { number: '8', name: 'Gold Woman', brand: 'Amouage', gender: 'Women', type: 'perfume' },
  { number: '9', name: 'Honour Woman', brand: 'Amouage', gender: 'Women', type: 'perfume' },
  { number: '10', name: 'Trussardi Donna', brand: 'Trussardi', gender: 'Women', type: 'perfume' },
  { number: '11', name: 'Delina Exclusif', brand: 'Parfums de Marly', gender: 'Women', type: 'perfume' },
  { number: '12', name: 'Vanilla Extasy', brand: 'Montale', gender: 'Women', type: 'perfume', searchTerms: ['vanilla'] },
  { number: '13', name: 'Another 13', brand: 'Le Labo', gender: 'Unisex', type: 'perfume' },
  { number: '14', name: 'Ocean Leather', brand: 'Memo Paris', gender: 'Unisex', type: 'perfume' },
  { number: '15', name: '24 Carat Pure Gold', brand: 'Lattafa Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '16', name: 'Arabians Tonka', brand: 'Montale', gender: 'Unisex', type: 'perfume' },
  { number: '17', name: 'Ani', brand: 'Nishane', gender: 'Unisex', type: 'perfume' },
  { number: '18', name: 'Hacivat', brand: 'Nishane', gender: 'Unisex', type: 'perfume' },
  { number: '19', name: 'Mimosa & Cardamom', brand: 'Jo Malone London', gender: 'Unisex', type: 'perfume' },
  { number: '20', name: 'Myrrh & Tonka', brand: 'Jo Malone London', gender: 'Unisex', type: 'perfume' },
  { number: '21', name: 'Vanille Fatale', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['vanilla'] },
  { number: '22', name: 'Ombré Leather', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['leather'] },
  { number: '23', name: 'Baccarat Rouge 540', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', type: 'perfume' },
  { number: '24', name: 'Baccarat Rouge 540 Extrait de Parfum', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', type: 'perfume' },
  { number: '25', name: 'Cuoium', brand: 'Orto Parisi', gender: 'Unisex', type: 'perfume' },
  { number: '26', name: 'Terroni', brand: 'Orto Parisi', gender: 'Unisex', type: 'perfume' },
  { number: '27', name: 'Troodos', brand: "Designed by Aquad'or", gender: 'Unisex', type: 'perfume' },
  { number: '28', name: 'Black Afgano', brand: 'Nasomatto', gender: 'Unisex', type: 'perfume' },
  { number: '29', name: 'More Than Words', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '30', name: 'XJ 1861 Naxos', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '31', name: 'Halfeti', brand: "Penhaligon's", gender: 'Unisex', type: 'perfume' },
  { number: '32', name: 'Black Phantom', brand: 'Kilian', gender: 'Unisex', type: 'perfume' },
  { number: '33', name: 'Kirkè', brand: 'Tiziana Terenzi', gender: 'Unisex', type: 'perfume' },
  { number: '34', name: 'Gold Knight', brand: 'Kilian', gender: 'Men', type: 'perfume' },
  { number: '35', name: 'Armani Code Cashmere', brand: 'Giorgio Armani', gender: 'Unisex', type: 'perfume' },
  { number: '36', name: 'Forbidden Games', brand: 'Kilian', gender: 'Women', type: 'perfume' },
  { number: '37', name: 'Good Girl Gone Bad', brand: 'Kilian', gender: 'Women', type: 'perfume' },
  { number: '38', name: 'African Leather', brand: 'Memo Paris', gender: 'Unisex', type: 'perfume', searchTerms: ['leather'] },
  { number: '39', name: 'Erba Pura', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '40', name: 'Oud Satin Mood', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '42', name: "Bal d'Afrique", brand: 'Byredo', gender: 'Unisex', type: 'perfume' },
  { number: '43', name: 'Fleur Narcotique', brand: 'Ex Nihilo', gender: 'Unisex', type: 'perfume', searchTerms: ['floral'] },
  { number: '44', name: 'Back to Black', brand: 'Kilian', gender: 'Unisex', type: 'perfume' },
  { number: '45', name: 'Casanova', brand: 'Tiziana Terenzi', gender: 'Unisex', type: 'perfume' },
  { number: '46', name: 'Orion', brand: 'Tiziana Terenzi', gender: 'Unisex', type: 'perfume' },
  { number: '47', name: 'Cassiopea', brand: 'Tiziana Terenzi', gender: 'Unisex', type: 'perfume' },
  { number: '48', name: 'Splendid Vanilla', brand: 'Roberto Cavalli', gender: 'Unisex', type: 'perfume', searchTerms: ['vanilla'] },
  { number: '49', name: 'Tobacolor', brand: 'Dior', gender: 'Unisex', type: 'perfume', searchTerms: ['tobacco'] },
  { number: '51', name: 'Mango Skin', brand: 'Vilhelm Parfumerie', gender: 'Unisex', type: 'perfume', searchTerms: ['fruity', 'mango'] },
  { number: '52', name: 'Roses Vanille', brand: 'Mancera', gender: 'Women', type: 'perfume', searchTerms: ['rose', 'vanilla'] },
  { number: '53', name: 'Madawi', brand: 'Arabian Oud', gender: 'Unisex', type: 'perfume' },
  { number: '54', name: 'Ganymede', brand: 'Marc-Antoine Barrois', gender: 'Unisex', type: 'perfume' },
  { number: '55', name: 'Heroine', brand: 'Boadicea the Victorious', gender: 'Women', type: 'perfume' },
  { number: '56', name: 'Oud for Happiness', brand: 'Initio Parfums Privés', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '57', name: 'Alexandria II', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '59', name: 'Sweet Morphine', brand: 'Ex Nihilo', gender: 'Women', type: 'perfume', searchTerms: ['sweet'] },
  { number: '60', name: '1001 Nights', brand: 'Arabian Oud', gender: 'Unisex', type: 'perfume' },
  { number: '61', name: 'Abyat', brand: 'Arabian Oud', gender: 'Unisex', type: 'perfume' },
  { number: '62', name: 'Scandal Dubai M', brand: "Designed by Aquad'or", gender: 'Men', type: 'perfume' },
  { number: '63', name: 'Scandal Dubai W', brand: "Designed by Aquad'or", gender: 'Women', type: 'perfume' },
  { number: '64', name: 'Scandalous Nights in Dubai W', brand: "Designed by Aquad'or", gender: 'Women', type: 'perfume' },
  { number: '65', name: 'So Dubai W (So Sexy Dubai W)', brand: "Designed by Aquad'or", gender: 'Women', type: 'perfume' },
  { number: '81', name: "Angel's Share", brand: 'Kilian', gender: 'Unisex', type: 'perfume' },
  { number: '82', name: 'Intense Cafe', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['coffee'] },
  { number: '83', name: 'Straight to Heaven', brand: 'Kilian', gender: 'Unisex', type: 'perfume' },
  { number: '84', name: 'Amber Musk', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['amber', 'musk'] },
  { number: '85', name: 'Sensual Instinct', brand: 'Montale', gender: 'Unisex', type: 'perfume' },
  { number: '86', name: 'Gentle Fluidity Gold', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', type: 'perfume' },
  { number: '87', name: 'Stallion Leather', brand: 'Carolina Herrera', gender: 'Unisex', type: 'perfume', searchTerms: ['leather'] },
  { number: '88', name: 'Kalan', brand: 'Parfums de Marly', gender: 'Unisex', type: 'perfume' },
  { number: '99', name: 'Pink Sugar', brand: 'Aquolina', gender: 'Women', type: 'perfume', searchTerms: ['sweet'] },
  { number: '100', name: 'Coco Vanille', brand: 'Mancera', gender: 'Women', type: 'perfume', searchTerms: ['coconut', 'vanilla'] },
  { number: '101', name: 'Gentleman Eau de Parfum', brand: 'Givenchy', gender: 'Men', type: 'perfume' },
  { number: '102', name: 'Lune Feline', brand: 'Atelier des Ors', gender: 'Unisex', type: 'perfume' },
  { number: '103', name: 'Versace Pour Homme Dylan Blue', brand: 'Versace', gender: 'Men', type: 'perfume' },
  { number: '104', name: 'Oud Ispahan', brand: 'Dior', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '105', name: 'Oud Bouquet Eau de Parfum', brand: 'Lancôme', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '106', name: 'Cuir', brand: 'Yves Saint Laurent', gender: 'Unisex', type: 'perfume', searchTerms: ['leather'] },
  { number: '107', name: 'Santal Dan Shā', brand: 'Giorgio Armani', gender: 'Unisex', type: 'perfume', searchTerms: ['sandalwood'] },
  { number: '108', name: 'Velvet Rose & Oud', brand: 'Jo Malone London', gender: 'Unisex', type: 'perfume', searchTerms: ['rose', 'oud'] },
  { number: '109', name: 'True Oud', brand: 'Carolina Herrera', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '110', name: 'The Library Collection Silver Oud', brand: 'Amouage', gender: 'Men', type: 'perfume', searchTerms: ['oud'] },
  { number: '111', name: 'Magic', brand: 'Al-Jazeera Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '112', name: 'Kalemat', brand: 'Arabian Oud', gender: 'Unisex', type: 'perfume' },
  { number: '113', name: 'Calabria', brand: 'Gissah', gender: 'Unisex', type: 'perfume' },
  { number: '114', name: 'My Way', brand: 'Giorgio Armani', gender: 'Women', type: 'perfume' },
  { number: '115', name: 'Scandal', brand: 'Jean Paul Gaultier', gender: 'Women', type: 'perfume' },
  { number: '116', name: 'Tuscan Leather', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['leather'] },
  { number: '117', name: 'Especially', brand: 'Escada', gender: 'Women', type: 'perfume' },
  { number: '118', name: 'Sauvage Elixir', brand: 'Dior', gender: 'Men', type: 'perfume' },
  { number: '119', name: 'Oud Malaki', brand: 'Chopard', gender: 'Men', type: 'perfume', searchTerms: ['oud'] },
  { number: '120', name: 'Reflection Man', brand: 'Amouage', gender: 'Men', type: 'perfume' },
  { number: '121', name: 'Sunshine Woman', brand: 'Amouage', gender: 'Women', type: 'perfume' },
  { number: '122', name: 'Journey Woman', brand: 'Amouage', gender: 'Women', type: 'perfume' },
  { number: '123', name: 'Memoir Woman', brand: 'Amouage', gender: 'Women', type: 'perfume' },
  { number: '124', name: 'Starry Nights', brand: 'Montale', gender: 'Unisex', type: 'perfume' },
  { number: '125', name: 'Aoud Leather', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['oud', 'leather'] },
  { number: '126', name: 'Honey Aoud', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['oud', 'honey'] },
  { number: '127', name: 'Wood on Fire', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['woody'] },
  { number: '128', name: 'Black Aoud', brand: 'Montale', gender: 'Men', type: 'perfume', searchTerms: ['oud'] },
  { number: '129', name: 'Oud', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '130', name: 'Lira', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '131', name: 'Cedrat Boise', brand: 'Mancera', gender: 'Unisex', type: 'perfume', searchTerms: ['citrus', 'woody'] },
  { number: '132', name: 'Wave Musk', brand: 'Mancera', gender: 'Unisex', type: 'perfume', searchTerms: ['musk'] },
  { number: '133', name: 'Red Tobacco', brand: 'Mancera', gender: 'Unisex', type: 'perfume', searchTerms: ['tobacco'] },
  { number: '134', name: 'Baraonda', brand: 'Nasomatto', gender: 'Unisex', type: 'perfume' },
  { number: '135', name: 'Narcotic Venus', brand: 'Nasomatto', gender: 'Women', type: 'perfume' },
  { number: '136', name: 'Stronger with You Leather', brand: 'Emporio Armani', gender: 'Men', type: 'perfume', searchTerms: ['leather'] },
  { number: '137', name: 'Scandal by Night', brand: 'Jean Paul Gaultier', gender: 'Women', type: 'perfume' },
  { number: '138', name: 'Layton', brand: 'Parfums de Marly', gender: 'Unisex', type: 'perfume' },
  { number: '139', name: 'Marfa', brand: 'Memo Paris', gender: 'Unisex', type: 'perfume' },
  { number: '140', name: 'Incense Oud', brand: 'Kilian', gender: 'Unisex', type: 'perfume', searchTerms: ['oud', 'incense'] },
  { number: '141', name: 'Fucking Fabulous', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume' },
  { number: '142', name: 'Oud Wood', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['oud', 'woody'] },
  { number: '143', name: 'Velvet Orchid', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['floral'] },
  { number: '144', name: 'Raghba', brand: 'Lattafa Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '145', name: 'Amathyst', brand: 'Lalique', gender: 'Women', type: 'perfume' },
  { number: '146', name: 'Encre Noire', brand: 'Lalique', gender: 'Men', type: 'perfume' },
  { number: '147', name: 'Amber Oud Gold Edition', brand: 'Al Haramain Perfumes', gender: 'Unisex', type: 'perfume', searchTerms: ['amber', 'oud'] },
  { number: '148', name: 'Mukhallath', brand: 'Al Haramain Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '149', name: 'Nomade', brand: 'Chloé', gender: 'Women', type: 'perfume' },
  { number: '150', name: 'Paradiso', brand: 'Roberto Cavalli', gender: 'Women', type: 'perfume' },
  { number: '151', name: 'Paradoxe', brand: 'Prada', gender: 'Women', type: 'perfume' },
  { number: '152', name: "L'Extase", brand: 'Nina Ricci', gender: 'Women', type: 'perfume' },
  { number: '153', name: 'Spicebomb', brand: 'Viktor&Rolf', gender: 'Men', type: 'perfume', searchTerms: ['spicy'] },
  { number: '154', name: 'Tobacco Blaze', brand: 'Rasasi', gender: 'Men', type: 'perfume', searchTerms: ['tobacco'] },
  { number: '155', name: 'Molecule 02', brand: 'Escentric Molecules', gender: 'Unisex', type: 'perfume' },
  { number: '156', name: 'Hareem Al Sultan Gold', brand: 'Khadlaj Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '157', name: 'Oud Eau de Parfum', brand: 'Acqua di Parma', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '158', name: 'Aventus Cologne', brand: 'Creed', gender: 'Men', type: 'perfume' },
  { number: '159', name: 'Grand Soir', brand: 'Maison Francis Kurkdjian', gender: 'Unisex', type: 'perfume' },
  { number: '160', name: 'Tygar', brand: 'Bvlgari', gender: 'Men', type: 'perfume' },
  { number: '161', name: 'White Aoud', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '162', name: 'Gypsy Water', brand: 'Byredo', gender: 'Unisex', type: 'perfume' },
  { number: '163', name: 'Pure Musk', brand: 'Lattafa Perfumes', gender: 'Unisex', type: 'perfume', searchTerms: ['musk'] },
  { number: '164', name: 'Versace Pour Femme Dylan Blue', brand: 'Versace', gender: 'Women', type: 'perfume' },
  { number: '165', name: 'Hayati', brand: 'Attar Collection', gender: 'Unisex', type: 'perfume' },
  { number: '166', name: 'Imagination', brand: 'Louis Vuitton', gender: 'Men', type: 'perfume' },
  { number: '167', name: 'Dior Homme Intense', brand: 'Dior', gender: 'Men', type: 'perfume' },
  { number: '168', name: 'Narciso Rodriguez for Him Bleu Noir', brand: 'Narciso Rodriguez', gender: 'Men', type: 'perfume' },
  { number: '169', name: "Terre d'Hermès", brand: 'Hermès', gender: 'Men', type: 'perfume' },
  { number: '170', name: 'So Sexy Scandal!', brand: 'Jean Paul Gaultier', gender: 'Women', type: 'perfume' },
  { number: '171', name: 'Pegasus', brand: 'Parfums de Marly', gender: 'Men', type: 'perfume' },
  { number: '172', name: 'Acqua di Giò', brand: 'Giorgio Armani', gender: 'Men', type: 'perfume' },
  { number: '173', name: 'Neroli Portofino', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['citrus'] },
  { number: '200', name: 'Femme', brand: "Designed by Aquad'or", gender: 'Women', type: 'perfume' },
  { number: '201', name: 'Stronger with You Tobacco', brand: 'Emporio Armani', gender: 'Men', type: 'perfume', searchTerms: ['tobacco'] },
  { number: '202', name: 'My Way Nectar', brand: 'Giorgio Armani', gender: 'Women', type: 'perfume' },
  { number: '203', name: 'Eros Flame', brand: 'Versace', gender: 'Men', type: 'perfume' },
  { number: '204', name: 'Fleur de Peau', brand: 'Diptyque', gender: 'Unisex', type: 'perfume', searchTerms: ['floral'] },
  { number: '205', name: 'Yara', brand: 'Lattafa Perfumes', gender: 'Women', type: 'perfume' },
  { number: '206', name: 'Accento Overdose', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '207', name: 'Pacific Chill', brand: 'Louis Vuitton', gender: 'Unisex', type: 'perfume' },
  { number: '208', name: 'Vanilla Sex', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['vanilla'] },
  { number: '209', name: 'Toy 2 Bubble Gum', brand: 'Moschino', gender: 'Women', type: 'perfume', searchTerms: ['sweet', 'fruity'] },
  { number: '210', name: 'Blue Talisman', brand: 'Ex Nihilo', gender: 'Unisex', type: 'perfume' },
  { number: '211', name: 'Casablanca Lily', brand: 'Byredo', gender: 'Unisex', type: 'perfume', searchTerms: ['floral', 'lily'] },
  { number: '212', name: 'Le Beau', brand: 'Jean Paul Gaultier', gender: 'Men', type: 'perfume' },
  { number: '213', name: 'Good Girl Blush', brand: 'Carolina Herrera', gender: 'Women', type: 'perfume' },
  { number: '214', name: 'Dahab', brand: 'Kajal', gender: 'Women', type: 'perfume' },
  { number: '215', name: 'Ameerat Al Arab', brand: 'Asdaaf', gender: 'Women', type: 'perfume' },
  { number: '216', name: 'Imperial Valley', brand: 'Gissah', gender: 'Unisex', type: 'perfume' },
  { number: '217', name: 'Scandal Le Parfum', brand: 'Jean Paul Gaultier', gender: 'Women', type: 'perfume' },
  { number: '218', name: 'Oud for Greatness', brand: 'Initio Parfums Privés', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '219', name: 'Insolence Eau de Parfum', brand: 'Guerlain', gender: 'Women', type: 'perfume' },
  { number: '220', name: 'Grey Vetiver', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['vetiver'] },
  { number: '221', name: 'Soleil Neige', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume' },
  { number: '222', name: 'Cherry Smoke', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['cherry', 'smoky'] },
  { number: '223', name: 'Rose Prick', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['rose'] },
  { number: '224', name: 'Noir de Noir', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume' },
  { number: '225', name: "L'Immensité", brand: 'Louis Vuitton', gender: 'Unisex', type: 'perfume' },
  { number: '226', name: 'Afternoon Swim', brand: 'Louis Vuitton', gender: 'Men', type: 'perfume' },
  { number: '227', name: 'Ombre Nomade', brand: 'Louis Vuitton', gender: 'Unisex', type: 'perfume' },
  { number: '228', name: 'Bracken Man', brand: 'Amouage', gender: 'Men', type: 'perfume' },
  { number: '229', name: 'Beach Hut Man', brand: 'Amouage', gender: 'Men', type: 'perfume' },
  { number: '230', name: 'Water Calligraphy', brand: 'Kilian', gender: 'Unisex', type: 'perfume' },
  { number: '231', name: 'Love and Tears', brand: 'Kilian', gender: 'Unisex', type: 'perfume' },
  { number: '232', name: 'Roses Musk', brand: 'Montale', gender: 'Unisex', type: 'perfume', searchTerms: ['rose', 'musk'] },
  { number: '233', name: 'Crazy In Love', brand: 'Montale', gender: 'Women', type: 'perfume' },
  { number: '234', name: 'Pure Gold', brand: 'Montale', gender: 'Unisex', type: 'perfume' },
  { number: '235', name: 'English Pear & Freesia', brand: 'Jo Malone London', gender: 'Unisex', type: 'perfume', searchTerms: ['fruity', 'floral'] },
  { number: '236', name: 'Blue Sapphire', brand: 'Boadicea the Victorious', gender: 'Unisex', type: 'perfume' },
  { number: '237', name: 'Chariot', brand: 'Boadicea the Victorious', gender: 'Unisex', type: 'perfume' },
  { number: '238', name: 'Corfu', brand: 'Memo Paris', gender: 'Unisex', type: 'perfume' },
  { number: '239', name: 'Changing Constance', brand: "Penhaligon's", gender: 'Women', type: 'perfume' },
  { number: '240', name: 'New York Nights', brand: 'Bond No 9', gender: 'Unisex', type: 'perfume' },
  { number: '241', name: 'Bianco Latte', brand: 'Giardini Di Toscana', gender: 'Unisex', type: 'perfume' },
  { number: '242', name: 'Khamrah Qahwa', brand: 'Lattafa Perfumes', gender: 'Unisex', type: 'perfume', searchTerms: ['coffee'] },
  { number: '243', name: 'Ameer Al Oudh Intense Oud', brand: 'Lattafa Perfumes', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '244', name: 'Asad', brand: 'Lattafa Perfumes', gender: 'Men', type: 'perfume' },
  { number: '245', name: 'The Blazing Mr Sam', brand: "Penhaligon's", gender: 'Men', type: 'perfume' },
  { number: '246', name: '40 Knots', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '247', name: 'Accento', brand: 'Xerjoff', gender: 'Unisex', type: 'perfume' },
  { number: '248', name: 'Gran Ballo', brand: 'Xerjoff', gender: 'Women', type: 'perfume' },
  { number: '249', name: "Love Don't Be Shy", brand: 'Kilian', gender: 'Women', type: 'perfume' },
  { number: '250', name: 'The Voice of The Snake', brand: 'Gucci', gender: 'Unisex', type: 'perfume' },
  { number: '251', name: 'Intense Oud', brand: 'Gucci', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '252', name: 'Santal Musc', brand: 'Narciso Rodriguez', gender: 'Unisex', type: 'perfume', searchTerms: ['sandalwood', 'musk'] },
  { number: '253', name: 'Promise', brand: 'Frederic Malle', gender: 'Unisex', type: 'perfume' },
  { number: '254', name: 'Blanche', brand: 'Byredo', gender: 'Women', type: 'perfume' },
  { number: '255', name: 'Arabians', brand: 'Montale', gender: 'Unisex', type: 'perfume' },
  { number: '256', name: 'California Dream', brand: 'Louis Vuitton', gender: 'Unisex', type: 'perfume' },
  { number: '257', name: 'City Of Stars', brand: 'Louis Vuitton', gender: 'Unisex', type: 'perfume' },
  { number: '258', name: 'Oud Maracujá', brand: 'Maison Crivelli', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '259', name: 'Althaïr', brand: 'Parfums de Marly', gender: 'Men', type: 'perfume' },
  { number: '260', name: 'Hawas for Him', brand: 'Rasasi', gender: 'Men', type: 'perfume' },
  { number: '261', name: 'Bitter Peach', brand: 'Tom Ford', gender: 'Unisex', type: 'perfume', searchTerms: ['fruity', 'peach'] },
  { number: '262', name: 'Vanilla 28', brand: 'Kayali Fragrances', gender: 'Unisex', type: 'perfume', searchTerms: ['vanilla'] },
  { number: '263', name: 'Vanilla Candy Rock Sugar 42', brand: 'Kayali Fragrances', gender: 'Women', type: 'perfume', searchTerms: ['vanilla', 'sweet'] },
  { number: '264', name: 'Oudgasm Smoky Oud 07', brand: 'Kayali Fragrances', gender: 'Unisex', type: 'perfume', searchTerms: ['oud', 'smoky'] },
  { number: '265', name: 'Khamrah', brand: 'Lattafa Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '266', name: 'Lost City (Atlantis)', brand: 'Gissah', gender: 'Unisex', type: 'perfume' },
  { number: '267', name: 'Amber Wood', brand: 'Ajmal', gender: 'Unisex', type: 'perfume', searchTerms: ['amber', 'woody'] },
  { number: '268', name: 'No 1', brand: 'Clive Christian', gender: 'Men', type: 'perfume' },
  { number: '269', name: 'Donna Born in Roma', brand: 'Valentino', gender: 'Women', type: 'perfume' },
  { number: '270', name: 'Uomo Born in Roma', brand: 'Valentino', gender: 'Men', type: 'perfume' },
  { number: '339', name: 'Santal 33', brand: 'Le Labo', gender: 'Unisex', type: 'perfume', searchTerms: ['sandalwood'] },
  { number: '340', name: 'Mojave Ghost', brand: 'Byredo', gender: 'Unisex', type: 'perfume' },
  { number: '341', name: 'Dubai Ruby', brand: 'Bond No 9', gender: 'Unisex', type: 'perfume' },
  { number: '342', name: 'Silver Dust', brand: '-', gender: 'Unisex', type: 'perfume' },
  { number: '343', name: 'Damascus', brand: 'Al-Jazeera Perfumes', gender: 'Unisex', type: 'perfume' },
  { number: '344', name: 'Shay Oud', brand: 'Anfasic', gender: 'Unisex', type: 'perfume', searchTerms: ['oud'] },
  { number: '345', name: 'Musk Al Qurashi', brand: '-', gender: 'Unisex', type: 'perfume', searchTerms: ['musk'] },
  { number: '346', name: 'Vanille Fleur', brand: 'M. Micallef', gender: 'Women', type: 'perfume', searchTerms: ['vanilla', 'floral'] },
  { number: '347', name: 'Fawakeh', brand: '-', gender: 'Unisex', type: 'perfume', searchTerms: ['fruity'] },
  { number: '348', name: 'Flowerbomb', brand: 'Viktor&Rolf', gender: 'Women', type: 'perfume', searchTerms: ['floral'] },
  { number: '349', name: 'Love Story', brand: 'Chloé', gender: 'Women', type: 'perfume' },
  { number: '350', name: 'Bonbon', brand: 'Viktor&Rolf', gender: 'Women', type: 'perfume', searchTerms: ['sweet'] },
  { number: '351', name: 'Coromandel Parfum', brand: 'Chanel', gender: 'Unisex', type: 'perfume' },
  { number: '352', name: 'Gabrielle Parfum', brand: 'Chanel', gender: 'Women', type: 'perfume' },
  { number: '353', name: 'Crystal Noir', brand: 'Versace', gender: 'Women', type: 'perfume' },
  { number: '354', name: 'Legend Intense', brand: 'Montblanc', gender: 'Men', type: 'perfume' },

  // Essence Oils (A01-A44)
  { number: 'A01', name: 'Jasmine', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['jasmine', 'floral'] },
  { number: 'A02', name: 'Musk Al Tahara', brand: 'Concentrated Musk Oil', gender: 'Unisex', type: 'essence-oil', searchTerms: ['musk'] },
  { number: 'A03', name: 'Arabian Jasmine', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['jasmine', 'floral'] },
  { number: 'A04', name: 'Tobacco Vanille', brand: 'Tom Ford', gender: 'Unisex', type: 'essence-oil', searchTerms: ['tobacco', 'vanilla'] },
  { number: 'A05', name: 'White Arabian Musk', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['musk'] },
  { number: 'A06', name: 'Vanilla Musk', brand: 'Concentrated Musk Oil', gender: 'Unisex', type: 'essence-oil', searchTerms: ['vanilla', 'musk'] },
  { number: 'A07', name: 'Pomegranate Musk', brand: 'Concentrated Musk Oil', gender: 'Unisex', type: 'essence-oil', searchTerms: ['pomegranate', 'musk', 'fruity'] },
  { number: 'A08', name: 'Green Apple', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['apple', 'fruity'] },
  { number: 'A09', name: 'Oriental Amber', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['amber'] },
  { number: 'A10', name: 'Cashmere Oud', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['oud'] },
  { number: 'A11', name: 'Musk Al Rafeef', brand: "Designed by Aquad'or", gender: 'Unisex', type: 'essence-oil', searchTerms: ['musk'] },
  { number: 'A12', name: 'Arabian Gardenia', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['gardenia', 'floral'] },
  { number: 'A13', name: 'Powdered Sandalwood', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['sandalwood', 'woody'] },
  { number: 'A14', name: 'Vanilla Chocolate', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['vanilla', 'chocolate', 'sweet'] },
  { number: 'A15', name: 'Patchouli', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['patchouli'] },
  { number: 'A16', name: 'Rouge Al Musk', brand: "Designed by Aquad'or", gender: 'Unisex', type: 'essence-oil', searchTerms: ['musk'] },
  { number: 'A17', name: 'Ruby Musk', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['musk'] },
  { number: 'A18', name: 'Chocolate', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['chocolate', 'sweet'] },
  { number: 'A19', name: 'Caramel', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['caramel', 'sweet'] },
  { number: 'A20', name: 'Abyad Oud', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['oud'] },
  { number: 'A21', name: 'Vanilla', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['vanilla'] },
  { number: 'A22', name: 'Arabian Magnolia', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['magnolia', 'floral'] },
  { number: 'A23', name: 'Tulip of the Desert', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['tulip', 'floral'] },
  { number: 'A24', name: 'Rose', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['rose', 'floral'] },
  { number: 'A25', name: 'Lost Cherry', brand: 'Tom Ford', gender: 'Unisex', type: 'essence-oil', searchTerms: ['cherry', 'fruity'] },
  { number: 'A26', name: 'Black Orchid', brand: 'Tom Ford', gender: 'Unisex', type: 'essence-oil', searchTerms: ['floral', 'orchid'] },
  { number: 'A27', name: 'Gold Yellow/Dubai Vanilla', brand: "Designed by Aquad'or", gender: 'Unisex', type: 'essence-oil', searchTerms: ['vanilla'] },
  { number: 'A28', name: 'White Oud of Arabia', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['oud'] },
  { number: 'A29', name: 'Cherry', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['cherry', 'fruity'] },
  { number: 'A30', name: 'Strawberry', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['strawberry', 'fruity'] },
  { number: 'A31', name: 'Lavender', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['lavender', 'floral'] },
  { number: 'A32', name: 'Coconut', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['coconut'] },
  { number: 'A33', name: 'Mango', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['mango', 'fruity'] },
  { number: 'A34', name: 'Peach', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['peach', 'fruity'] },
  { number: 'A35', name: 'Blueberry', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['blueberry', 'fruity'] },
  { number: 'A36', name: 'Ylang-Ylang', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['ylang-ylang', 'floral'] },
  { number: 'A37', name: 'Vetiver', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['vetiver'] },
  { number: 'A38', name: 'Coffee', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['coffee'] },
  { number: 'A39', name: 'Marijuana', brand: '-', gender: 'Unisex', type: 'essence-oil' },
  { number: 'A40', name: 'Ward Musk (Arabic Rose Musk)', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['rose', 'musk'] },
  { number: 'A41', name: 'Vanilla Cinnamon', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['vanilla', 'cinnamon', 'spicy'] },
  { number: 'A42', name: 'White Aoud', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['oud'] },
  { number: 'A43', name: 'Leather of Arabia', brand: '-', gender: 'Unisex', type: 'essence-oil', searchTerms: ['leather'] },
  { number: 'A44', name: 'Rose Al Tahara', brand: "Designed by Aquad'or", gender: 'Unisex', type: 'essence-oil', searchTerms: ['rose', 'musk'] },
];

/**
 * Search products by note, name, brand, or gender
 */
export function searchCatalogue(query: string): CatalogueProduct[] {
  const lowercaseQuery = query.toLowerCase().trim();

  return catalogueProducts.filter(product => {
    const searchableText = [
      product.name,
      product.brand,
      product.gender,
      ...(product.searchTerms || [])
    ].join(' ').toLowerCase();

    return searchableText.includes(lowercaseQuery);
  });
}

/**
 * Get products by gender
 */
export function getProductsByGender(gender: 'Men' | 'Women' | 'Unisex'): CatalogueProduct[] {
  return catalogueProducts.filter(p => p.gender === gender);
}

/**
 * Get products by type
 */
export function getProductsByType(type: 'perfume' | 'essence-oil' | 'body-lotion'): CatalogueProduct[] {
  return catalogueProducts.filter(p => p.type === type);
}
